---
# tasks file for rl_testrole


---
# tasks file for rl_install_openjdk

- name: Create a directory for openjdk
  become: true
  ansible.builtin.file:
    path: "{{ app_home }}/openjdk"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: checking if has already been downloaded 
  connection: local
  stat:
    path: "{{ openjdk_package }}"
  register: regOpenjdk

- name: Download amazon coretto
  connection: local 
  ansible.builtin.get_url:
    url: "{{ url_openjdk_bin }}"
    dest: "{{ software_repo }}"
  when: regOpenjdk.stat.exists == False
 
- name: check if openjsk has already been extracted on target
  stat:
    path: "{{ app_home }}/openjdk/amazon-corretto-{{ openjdk_version }}-linux-x64"
  register: regOpenjdkDir

- name: Extract "{{ openjdk_package }}" into {{ app_home }}
  become: true
  ansible.builtin.unarchive:
    src: "{{ openjdk_package }}"
    dest: "{{ app_home }}/openjdk"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  when: regOpenjdkDir.stat.isdir == False

- name: Create a symbolic link for java
  become: true
  ansible.builtin.file:
    src: "{{ app_home }}/openjdk/amazon-corretto-{{ openjdk_version }}-linux-x64"
    dest: "{{ app_home }}/java"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    state: link
